"""Format review results as Markdown."""

from .models import Issue, ReviewResult


class ReviewFormatter:
    """Formats ReviewResult into GitHub-flavored Markdown."""

    def _format_issue(self, issue: Issue) -> str:
        """Format a single issue as markdown."""
        parts = []

        # File and line reference
        if issue.line:
            parts.append(f"**`{issue.file}:{issue.line}`**")
        else:
            parts.append(f"**`{issue.file}`**")

        # Description
        parts.append(f"\n{issue.description}")

        # Suggestion
        if issue.suggestion:
            parts.append(f"\n💡 **Suggestion:** {issue.suggestion}")

        return "\n".join(parts)

    def format_review(self, result: ReviewResult, pr_url: str = "") -> str:
        """Format ReviewResult as Markdown comment."""
        sections = []

        # Header
        sections.append("# 🤖 AI Code Review\n")

        # Summary
        sections.append("## Summary")
        sections.append(result.summary)
        sections.append("")

        # Blocking Issues
        if result.blocking_issues:
            sections.append("## 🚨 Blocking Issues")
            sections.append("_These issues must be addressed before merging._\n")
            for idx, issue in enumerate(result.blocking_issues, 1):
                sections.append(f"### {idx}. {issue.file}")
                sections.append(self._format_issue(issue))
                sections.append("")
        else:
            sections.append("## ✅ No Blocking Issues\n")

        # Non-Blocking Issues
        if result.non_blocking_issues:
            sections.append("## 💡 Non-Blocking Issues")
            sections.append("_These suggestions can improve code quality._\n")
            for idx, issue in enumerate(result.non_blocking_issues, 1):
                sections.append(f"### {idx}. {issue.file}")
                sections.append(self._format_issue(issue))
                sections.append("")

        # Tests Assessment
        if result.tests_assessment:
            sections.append("## 🧪 Tests")
            sections.append(result.tests_assessment)
            sections.append("")

        # Risks
        if result.risks:
            sections.append("## ⚠️ Risks")
            for risk in result.risks:
                sections.append(f"- {risk}")
            sections.append("")

        # Suggested Improvements
        if result.suggested_improvements:
            sections.append("## 🚀 Suggested Improvements")
            for improvement in result.suggested_improvements:
                sections.append(f"- {improvement}")
            sections.append("")

        # Footer
        sections.append("---")
        sections.append("_Generated by AI Code Review using GigaChat_")
        if pr_url:
            sections.append(f"_Review for [{pr_url}]({pr_url})_")

        return "\n".join(sections)
