"""Post review comments to GitHub using MCP."""

import asyncio
import os
import shlex
import sys
import logging
from typing import Optional

sys.path.insert(0, os.path.join(os.path.dirname(__file__), "../progect_assistant"))

from assistant.mcp_client import MCPStdioClient

from .config import CodeReviewConfig

logger = logging.getLogger(__name__)


class ReviewPoster:
    """Posts review comments to GitHub via MCP."""

    def __init__(self, config: CodeReviewConfig):
        self.config = config
        env = {
            "GITHUB_PERSONAL_ACCESS_TOKEN": config.github_token,
        }
        self.client = MCPStdioClient(
            command=shlex.split(config.mcp_github_command),
            name="github-mcp-poster",
            env=env,
        )

    async def _list_tool_names(self) -> set[str]:
        """Return available MCP tool names, ignoring failures."""
        try:
            tools = await self.client.list_tools()
            return {t.get("name", "") for t in tools if isinstance(t, dict)}
        except Exception as e:
            logger.warning("github-mcp-poster: failed to list tools: %s", e)
            return set()

    def _build_pr_review_payload(self, pr_number: int, body: str) -> tuple[str, dict]:
        return (
            "create_pull_request_review",
            {
                "owner": self.config.repo_owner,
                "repo": self.config.repo_name,
                "pull_number": pr_number,
                "body": body,
                "event": "COMMENT",
            },
        )

    def _build_issue_comment_payload(self, pr_number: int, body: str) -> tuple[str, dict]:
        return (
            "create_issue_comment",
            {
                "owner": self.config.repo_owner,
                "repo": self.config.repo_name,
                "issue_number": pr_number,  # PRs are issues in GitHub API
                "body": body,
            },
        )

    def _build_pr_comment_payload(self, pr_number: int, body: str) -> tuple[str, dict]:
        # Some MCP GitHub servers expose a PR-specific comment tool
        return (
            "create_pull_request_comment",
            {
                "owner": self.config.repo_owner,
                "repo": self.config.repo_name,
                "pull_number": pr_number,
                "body": body,
            },
        )

    async def post_review(self, pr_number: int, review_markdown: str) -> bool:
        """Post review comment to PR."""
        max_retries = 3
        retry_delay = 2.0

        available_tools = await self._list_tool_names()
        candidates = []

        # Prefer dedicated PR review tool if present
        if not available_tools or "create_pull_request_review" in available_tools:
            candidates.append(self._build_pr_review_payload(pr_number, review_markdown))
        # Fallback to issue comment tool if available
        if not available_tools or "create_issue_comment" in available_tools:
            candidates.append(self._build_issue_comment_payload(pr_number, review_markdown))
        # Extra fallback for PR comment tool variants
        if "create_pull_request_comment" in available_tools:
            candidates.append(self._build_pr_comment_payload(pr_number, review_markdown))

        if not candidates:
            raise RuntimeError(
                f"No suitable MCP tools to post review. Available: {sorted(available_tools)}"
            )

        for attempt in range(max_retries):
            try:
                for tool_name, payload in candidates:
                    try:
                        await self.client.call_tool(tool_name, payload)
                        return True
                    except Exception as e:
                        # Unknown tool? try next candidate
                        logger.warning("github-mcp-poster: %s failed: %s", tool_name, e)
                        continue

                # If we reach here, all candidates failed for this attempt
                raise RuntimeError("All MCP posting tools failed")

            except Exception as e:
                if attempt < max_retries - 1:
                    # Exponential backoff
                    await asyncio.sleep(retry_delay * (2 ** attempt))
                else:
                    raise RuntimeError(f"Failed to post review after {max_retries} attempts: {e}")

        return False

    async def post_error_comment(self, pr_number: int, error_message: str) -> bool:
        """Post error comment to PR."""
        comment = f"""# ❌ AI Code Review Failed

An error occurred while generating the code review:

```
{error_message}
```

Please check the workflow logs for more details.

_Generated by AI Code Review_
"""
        return await self.post_review(pr_number, comment)

    async def post_size_warning(self, pr_number: int, files_count: int, lines_count: int) -> bool:
        """Post size warning comment to PR."""
        comment = f"""# ⚠️ PR Size Exceeds Review Limits

This PR is too large for automatic AI review:
- **Files changed:** {files_count} (limit: {self.config.max_files_per_review})
- **Lines changed:** {lines_count} (limit: {self.config.max_lines_per_review})

**Suggestions:**
1. Split this PR into smaller, focused changes
2. Separate refactoring from feature additions
3. Move tests to a separate PR if appropriate

Smaller PRs are easier to review and less likely to introduce bugs.

_Generated by AI Code Review_
"""
        return await self.post_review(pr_number, comment)

    async def close(self) -> None:
        """Close MCP client connection."""
        await self.client.close()
